[project]
name = "ontoma"
version = "2.0.0"
description = "Ontology mapping for Open Targets"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=6.30.1",
    "numpy>=2.2.6",
    "rapidfuzz>=3.14.1",
    "torch>=2.8.0",
    "transformers>=4.57.0",
    "pyspark==3.5.7",
    "spark-nlp==6.1.5",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/ontoma"]
