[project]
name = "ontoma"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=6.30.1",
    "numpy>=2.2.6",
    "pyspark==3.3.4",
    "spark-nlp>=6.1.3",
]
