[project]
name = "ontoma"
version = "2.1.1"
description = "Ontology mapping for Open Targets"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=6.30.1",
    "numpy>=2.2.6",
    "pyspark==3.5.7",
    "spark-nlp==6.1.5",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/ontoma"]

[tool.hatch.build.targets.sdist]
include = ["src/**", "README.md", "LICENSE"]
