[project]
name = "ontoma"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=6.30.1",
    "numpy>=2.2.6",
    "pyspark==3.3.4",
    "rapidfuzz>=3.14.1",
    "spark-nlp>=6.1.3",
    "torch>=2.8.0",
    "transformers>=4.57.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/ontoma"]
